#src/OC/PlateformBundle/Ressources/Config/routing.yml
oc_plateform_home:
    path: /plateform
    defaults: { _controller:OCPlateformBundle:Advert:index }

oc_plateform_view:
    path: /plateform/advert/{id}
    defaults: { _controller:OCPlateformBundle:Advert:view }
