#src/OC/PlateformBundle/Ressources/Config/routing.yml
oc_plateform_home:
    path: /plateform
    defaults: { _controller:OCPlateformBundle:Advert:index }

oc_plateform_view:
    path: /plateform/advert/{id}
    defaults: { _controller:OCPlateformBundle:Advert:view }

oc_plateform_add:
    path: /plateform/add
    defaults: { _controller:OCPlateformBundle:Advert:add }

oc_plateform_view_slug:
    path: /plateform/{year}/{slug}.{format}
    defaults: 
        _controller: OCPlateformBundle:Advert:viewSlug
    requirements:
        year: \d{4}
        format: html|xml